
const classe61 = ["Domenico Agostino",
  "Mihai Badia",
  "Riccardo Becattini",
  "Manuel Benini",
  "Bruno Bernardini",
  "Guido Buono",
  "Pierluigi Cancellaro",
  "Francesco Cataletto",
  "Stefano Cravotta",
  "Giovanni Crispino",
  "Giancarlo Croce",
  "Enrico De Stefano",
  "Silvia Dugato",
  "Carlo Duminuco Del Monte",
  "Francesco Ercoli",
  "Luca Gaddini",
  "Marco Gagliano",
  "Cristina Gasperini",
  "Gabriele Giusti",
  "Chiara Grillo",
  "Manuela Ienuso",
  "Michele Iliescu",
  "Ketevan Jorjoliani",
  "Renato Lami",
  "Davide Manciucca",
  "Emanuele Mastronardi",
  "Luca Mazzarini",
  "Daniele Monteleone",
  "Salvatore Olivieri",
  "Leonardo Pellegrini",
  "Agostino Piquè",
  "Davide Pizzolla",
  "Antonio Pollo",
  "Ivan Russo",
  "Amanjit Singh",
  "Sebastiano Visco"
  ];



